apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: '0 0 1 * *'
  startingDeadlineSeconds: 30
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 0
      template:
        spec:
          containers:
            - name: django-clearsessions
              image: stmkv03/django:v1.0
              imagePullPolicy: Always
              command:
                - /bin/bash
                - -c
                - python manage.py clearsessions
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: django-secret
                      key: DATABASE_URL
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: django-secret
                      key: SECRET_KEY
                - name: DEBUG
                  valueFrom:
                    secretKeyRef:
                      name: django-secret
                      key: DEBUG
                - name: ALLOWED_HOSTS
                  valueFrom:
                    secretKeyRef:
                      name: django-secret
                      key: ALLOWED_HOSTS
          restartPolicy: OnFailure
