apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL2RlbW86ZGVtb0BwZy1kamFuZ28tcG9zdGdyZXNxbDo1NDMyL2RlbW8K
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLXBpLXAmJDN1cXJ0cHJfOGpvYiEqOTgkLV4hXnBeNGs9eHMqZjQjI2cwM2RjN29oaGpx
  DEBUG: VHJ1ZQ==
  ALLOWED_HOSTS: c3Rhci1idXJnZXIudGVzdCwxOTIuMTY4LjU5LjEwMwo=
