apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9lZHUtc3dlZXQtc2FuZGVyc29uOlc5X2ZpVkpFNGpFQ0tpd0BAcmMxYi1xaXR3a3cwa3dlZm5oYXN0Lm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9lZHUtc3dlZXQtc2FuZGVyc29uP3NzbG1vZGU9cmVxdWlyZQ==
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLXBpLXAmJDN1cXJ0cHJfOGpvYiEqOTgkLV4hXnBeNGs9eHMqZjQjI2cwM2RjN29oaGpx
  DEBUG: VHJ1ZQ==
  ALLOWED_HOSTS: ZWR1LXN3ZWV0LXNhbmRlcnNvbi5zaXJpdXMtazhzLmR2bW4ub3Jn
